kind: pipeline
type: kubernetes
name: default
steps:
- name: publish
  image: plugins/docker
  settings:
   repo: mohamedhamza/privateip
   tags: [ "${DRONE_COMMIT_SHA:0:8}", "latest" ]
   username:
    from_secret: docker_username
   password:
    from_secret: docker_password
